# Generated by Django 4.0.5 on 2022-07-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=60)),
                ('occupation', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
    ]
