# Generated by Django 4.0.5 on 2022-07-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
